version: "3.9"
services:
  db:
    image: "mysql:8.0.29"
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blog
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3600:3306"
volumes:
  db_data:

  