version: "3.9"
services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://db/blog
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run
  db:
    image: "mysql:8.0.29"
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=blog
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - "3600:3600"
volumes:
  mysql_data:
  mysql_config:

  